### ISSUE TITLE
nrwl nx and jest causes SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by leon** [juggle/resize-observer#82]
**Describe the bug**
I'm using nrwl/nx and jest to build my angular app.
I want to use @juggle/resize-observer in the project.
It works great when developing and in production,
but jest doesn't seem to like the library.

When running my tests I get

```
Test suite failed to run

    /Users/leon/Projects/myproject/node_modules/@juggle/resize-observer/lib/ResizeObserver.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import { ResizeObserverController } from './ResizeObserverController';
                                                                                             ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      1 | import { Observable } from 'rxjs'
    > 2 | import { ResizeObserver } from '@juggle/resize-observer'
        | ^
      3 | 
      4 | /**
      5 |  * Create an observable which will emit every time the passed in elements get resized

      at ScriptTransformer._transformAndBuildScript (../../../node_modules/@jest/transform/build/ScriptTransformer.js:537:17)
      at ScriptTransformer.transform (../../../node_modules/@jest/transform/build/ScriptTransformer.js:579:25)
      at Object.<anonymous> (../../view/ui/src/lib/resize-observable.ts:2:1)

```

I know this isn't your problem, it's a jest problem, but I thought that I won't be the only one getting this error, so I thought we could try to find a solution together.

**To Reproduce**
create a nx workspace with an angular app
add a component
import `@juggle/resize-observer` in the component
then run npm test

**Expected behavior**
That the library should work when testing using jest.

**Frameworks/Libraries used**
Angular
Jest

**Desktop (please complete the following information):**
 - OS: mac catalina
 - Browser chrome
 - Version 78

**Additional context**
It has something to do with how the library is packaged and that it has es2015 imports.
maybe we need to have a both a "main" field in the package.json which points to a commonjs version, and a "module" version which points to a es2015 version?

**Comment by TremayneChrist** [comment]
Thanks @leon I'll have a think about this.

**Comment by TomOne** [comment]
This issue also happens whenever this library is used with SSR as Node.js doesn’t support ES2015 imports.

**Comment by justwright** [comment]
As a temporary workaround, you can add the following to your jest config:

`transformIgnorePatterns: ['/node_modules/(?!@juggle/resize-observer)']` 

https://jestjs.io/docs/en/configuration#transformignorepatterns-array-string

**Comment by ksmithut** [comment]
If you're using create-react-app, you can't set the "transformIgnorePatterns" option unless you eject

**Comment by leon** [comment]
@TremayneChrist Where you able to find a way to get this to work?

**Comment by tom-s** [comment]
I have the same issue with SSR. Any plan to release an es5 version ?

**Comment by TremayneChrist** [comment]
So to get this to work there needs to be a UMD build supplied as the main entrypoint and then keep the ESM build for the module entrypoint.

In theory, it should be safe to just replace the main entrypoint -  If anyone has any concerns about this, I can push it into a major release.

**Comment by TremayneChrist** [comment]
So there's a problem with this, as the library currently outputs both default and named exports. This means that there would be inconsistencies between the ESM and UMD builds, when importing the module.

Trying to see if there is a better solution as this would require a major release and for default exports to be removed.

**Comment by Mike-Dax** [comment]
It would be considered bad style to mix both named and default exports.

commonjs only has the single `exports` object, there's no default export other than directly setting `exports` to `ResizeObserver`.

This library doesn't work currently for people that aren't using a bundler consuming your ESM.

If you wanted you could export both in a named exports mode. The bundler would see the `__esModule` property set and just assign the `default` key when the developer tries to do a default import. 

Then you can drop default exports in a major version bump.

**Comment by TremayneChrist** [comment]
Thanks @Mike-Dax I think it's best to push these changes into the next major version, based on the comments in the PR. The mix of default and named came from keeping backwards compatibility.

Now trialing support in a prerelease version with named-only exports, if anyone fancies giving it a try.
```shell
npm i @juggle/resize-observer@next
```
https://github.com/juggle/resize-observer/releases/tag/v3.0.0-0

**Comment by drcmda** [comment]
is `next` safe to use? i am using the module in a lib of mine [react-use-measure](https://github.com/react-spring/react-use-measure), which is then used by bigger projects with a bit of a user-base, i'm catching complaints from ssr users atm.

**Comment by TremayneChrist** [comment]
3.0.0-0 should be safe to use but please fix the version. Other prereleases will be released over the next few days which could include changes to `contentBoxSize`, `borderBoxSize` and `devicePixelContentBox' outputs. `contentRect` will not change.

**Comment by drcmda** [comment]
maybe you're the right person to ask now that you mention it, we use none of this, because contentRect gives wrong data in nested situations, see: https://github.com/react-spring/react-use-measure we basically just need the trigger. do you know anything about this? i really wonder how the spec can be so shortsighted that the smallest little scroll area basically makes all values invalid. or does this just happen because the browsers have yet to implement it correctly?

**Comment by TremayneChrist** [comment]
`contentRect` only gives the position of the `content-box` relative to the element you're observing. It's also been deprecated in the specification, which is probably down to it having no real value and also because RO is an API for dimensions, rather than positions. Getting the actual position of an element relative to the document, without going through the tree, I think is still only possible with `getBoundingClientRect()`, which is what you're already using. The only problem with this Rect, is that it's affected by transforms, so scaling and translation will skew the values.

RO always outputs actual values, for width and height. This is so that anything using these values, can do so, knowing that they will not modify the document layout. The problem is, is that `contentRect` returns outer dimensions minus padding, which could be wrong for your use. In this case you would need to use the `border-box` RO option, however, this is not implement natively in some browsers, so additional checks would need to be added.

**Comment by TremayneChrist** [comment]
Fixed in v3.0.0

**Comment by adidahiya** [comment]
@TremayneChrist what was actually fixed about this in v3.0.0? I'm still getting this error with @juggle/resize-observer v3.3.1:

```
(node:249) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
/home/circleci/project/node_modules/@juggle/resize-observer/lib/DOMRectReadOnly.js:1
import { freeze } from './utils/freeze';
^^^^^^
SyntaxError: Cannot use import statement outside a module
```

I'm using Node 12. I'd like to be able to use @juggle/resize-observer without transforming through Babel.

One potential solution might be to add `"type": "module"` to your package.json, so that Node (and in my case Mocha, which I'm using to run the tests which produce this module loading error) knows to parse the files as ES modules.

**Comment by TremayneChrist** [comment]
Hi @adidahiya what is the exact version of node you are using?

**Comment by adidahiya** [comment]
@TremayneChrist node v12.22.7
